### ISSUE TITLE
install fails when apt update errors

### ISSUE THREAD

**Issue by antempus** [aacebedo/i3-xfce#1]
When apt update has a repo that errors, the install fails ungracefully. 

Ubuntu 16.04
`
stryakr@XPS-9550:~/i3-xfce/bin$ sudo ./i3-xfce install

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [zsh : include] ***********************************************************
included: /home/stryakr/i3-xfce/share/i3-xfce/roles/zsh/tasks/install.yml for localhost

TASK [zsh : apt] ***************************************************************
failed: [localhost] => (item=[u'zsh', u'tree', u'git']) => {"cmd": "apt-get update '&&' apt-get install python-apt -y -q --force-yes", "failed": true, "item": ["zsh", "tree", "git"], "msg": "W: http://dl.google.com/linux/chrome/deb/dists/stable/Release.gpg: Signature by key 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 uses weak digest algorithm (SHA1)\nW: http://dl.google.com/linux/chrome/deb/dists/stable/Release.gpg: Signature by key 3B068FB4789ABE4AEFA3BB491397BC53640DB551 uses weak digest algorithm (SHA1)\nW: The repository 'http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial Release' does not have a Release file.\nE: Failed to fetch http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found\nE: Failed to fetch http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found\nE: Some index files failed to download. They have been ignored, or old ones used instead.", "rc": 100, "stderr": "W: http://dl.google.com/linux/chrome/deb/dists/stable/Release.gpg: Signature by key 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 uses weak digest algorithm (SHA1)\nW: http://dl.google.com/linux/chrome/deb/dists/stable/Release.gpg: Signature by key 3B068FB4789ABE4AEFA3BB491397BC53640DB551 uses weak digest algorithm (SHA1)\nW: The repository 'http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial Release' does not have a Release file.\nE: Failed to fetch http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found\nE: Failed to fetch http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found\nE: Some index files failed to download. They have been ignored, or old ones used instead.\n", "stdout": "Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease\nIgn:2 http://dl.google.com/linux/chrome/deb stable InRelease\nHit:3 http://dl.google.com/linux/chrome/deb stable Release\nGet:4 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [94.5 kB]\nGet:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [93.3 kB]\nIgn:6 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial InRelease\nHit:8 http://repository.spotify.com stable InRelease\nHit:9 http://ppa.launchpad.net/dockbar-main/ppa/ubuntu xenial InRelease\nHit:10 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu xenial InRelease\nHit:11 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease\nHit:12 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease\nHit:13 http://ppa.launchpad.net/webupd8team/sublime-text-3/ubuntu xenial InRelease\nHit:14 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease\nIgn:15 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial Release\nIgn:16 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 Packages\nIgn:17 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main i386 Packages\nIgn:18 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main all Packages\nIgn:19 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en_US\nIgn:20 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en\nIgn:21 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 DEP-11 Metadata\nIgn:22 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main DEP-11 64x64 Icons\nIgn:16 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 Packages\nIgn:17 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main i386 Packages\nIgn:18 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main all Packages\nIgn:19 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en_US\nIgn:20 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en\nIgn:21 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 DEP-11 Metadata\nIgn:22 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main DEP-11 64x64 Icons\nIgn:16 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 Packages\nIgn:17 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main i386 Packages\nIgn:18 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main all Packages\nIgn:19 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en_US\nIgn:20 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en\nIgn:21 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 DEP-11 Metadata\nIgn:22 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main DEP-11 64x64 Icons\nIgn:16 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 Packages\nIgn:17 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main i386 Packages\nIgn:18 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main all Packages\nIgn:19 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en_US\nIgn:20 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en\nIgn:21 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 DEP-11 Metadata\nIgn:22 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main DEP-11 64x64 Icons\nIgn:16 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 Packages\nIgn:17 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main i386 Packages\nIgn:18 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main all Packages\nIgn:19 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en_US\nIgn:20 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en\nIgn:21 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 DEP-11 Metadata\nIgn:22 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main DEP-11 64x64 Icons\nErr:16 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 Packages\n  404  Not Found\nErr:17 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main i386 Packages\n  404  Not Found\nIgn:18 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main all Packages\nIgn:19 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en_US\nIgn:20 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en\nIgn:21 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 DEP-11 Metadata\nIgn:22 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main DEP-11 64x64 Icons\nFetched 188 kB in 9s (19.0 kB/s)\nReading package lists...\n", "stdout_lines": ["Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease", "Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease", "Hit:3 http://dl.google.com/linux/chrome/deb stable Release", "Get:4 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [94.5 kB]", "Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [93.3 kB]", "Ign:6 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial InRelease", "Hit:8 http://repository.spotify.com stable InRelease", "Hit:9 http://ppa.launchpad.net/dockbar-main/ppa/ubuntu xenial InRelease", "Hit:10 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu xenial InRelease", "Hit:11 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease", "Hit:12 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease", "Hit:13 http://ppa.launchpad.net/webupd8team/sublime-text-3/ubuntu xenial InRelease", "Hit:14 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease", "Ign:15 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial Release", "Ign:16 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 Packages", "Ign:17 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main i386 Packages", "Ign:18 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main all Packages", "Ign:19 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en_US", "Ign:20 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en", "Ign:21 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 DEP-11 Metadata", "Ign:22 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main DEP-11 64x64 Icons", "Ign:16 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 Packages", "Ign:17 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main i386 Packages", "Ign:18 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main all Packages", "Ign:19 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en_US", "Ign:20 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en", "Ign:21 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 DEP-11 Metadata", "Ign:22 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main DEP-11 64x64 Icons", "Ign:16 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 Packages", "Ign:17 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main i386 Packages", "Ign:18 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main all Packages", "Ign:19 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en_US", "Ign:20 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en", "Ign:21 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 DEP-11 Metadata", "Ign:22 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main DEP-11 64x64 Icons", "Ign:16 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 Packages", "Ign:17 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main i386 Packages", "Ign:18 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main all Packages", "Ign:19 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en_US", "Ign:20 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en", "Ign:21 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 DEP-11 Metadata", "Ign:22 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main DEP-11 64x64 Icons", "Ign:16 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 Packages", "Ign:17 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main i386 Packages", "Ign:18 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main all Packages", "Ign:19 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en_US", "Ign:20 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en", "Ign:21 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 DEP-11 Metadata", "Ign:22 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main DEP-11 64x64 Icons", "Err:16 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 Packages", "  404  Not Found", "Err:17 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main i386 Packages", "  404  Not Found", "Ign:18 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main all Packages", "Ign:19 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en_US", "Ign:20 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main Translation-en", "Ign:21 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main amd64 DEP-11 Metadata", "Ign:22 http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu xenial/main DEP-11 64x64 Icons", "Fetched 188 kB in 9s (19.0 kB/s)", "Reading package lists..."]}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   

An error occured: Error when executing ansible
`

**Comment by aacebedo** [comment]
Done, the verbose mode is now the default way to have the install log.
Regards
