### ISSUE TITLE
Error when executing ansible

### ISSUE THREAD

**Issue by shakibamoshiri** [aacebedo/i3-xfce#2]
Hello . After addeding ppa I try to `sudo i3-xfce install` and gave me an error (ubuntu 16.04 LTS)

`fatal: [localhost]: FAILED! => {"changed": false, "cmd": "apt-key add -", "failed": true, "msg": "gpg: no valid OpenPGP data found.", "rc": 2, "stderr": "gpg: no valid OpenPGP data found.\n", "stdout": "", "stdout_lines": []}`

`localhost                  : ok=2    changed=0    unreachable=0    failed=1
`

**Comment by aacebedo** [comment]
Hi,
Thank you for your feedback.

Can you tell me how did you install i3-xfce and the version you've downloaded (I am currently trying to release the version with the fix for  #1 but launchpad is kind of annoying).

Is it a fresh install of 16.04 or did you try to run i3-xfce on an already existing installation ?

Regards

**Comment by aacebedo** [comment]
There is a chance that it is the chrome install which is faulty. 
I am going to remove the install of chrome as it does not have any reason to be installed with this app.

Regards

**Comment by shakibamoshiri** [comment]
Hello, I tried to install by PPA, because in manual method (./setup.py install -prefix=) ,gave me an ERROR, too.
Also, I have a big problem because of I am living in Iran. I have to turn on my VPN before using this command "sudo install i3-xfce" ( Ah! google :( )
Your second question is NO. It is a fresh install. Anyway I try it again and report the result.
[ I am so sorry, my English writing is not very well ]

**Comment by shakibamoshiri** [comment]
This is a video that I take a screencast from my konsols. I hope it would be useful.

[Kazam_screencast_00003.mp4.zip](https://github.com/aacebedo/i3-xfce/files/274219/Kazam_screencast_00003.mp4.zip)

**Comment by shakibamoshiri** [comment]
And this video is about `sudo i3-xfce install` with VPN and without VPN
[Kazam_screencast_00003.mp4.zip](https://github.com/aacebedo/i3-xfce/files/274237/Kazam_screencast_00003.mp4.zip)

**Comment by aacebedo** [comment]
Thanks for your feedback.
I am currently working on the issue. It hasnt been fixed yet :( hope to finish this weekend.
I have a lot of issues with launchpad so I am going to switch to Travis and bintray. Please consider the ppa as not relevant.

I am not an English native speaker either so don't worry about wording  :)

**Comment by ghost** [comment]
Same issues as @k-five, will wait for you to come up with a solution! Keep up the great work!

**Comment by aacebedo** [comment]
Hi! Thanks for your answer! 
I've released a new version solving the issue on pypi. 
You shall remove the package with apt remove i3-xfce and try pip3 install i3-xfce. 
Regards
