### ISSUE TITLE
"i3-xfce install" command fails (missing ansible package) [added information!]

### ISSUE THREAD

**Issue by j-h-m** [aacebedo/i3-xfce#9]
Added Information:
I installed ansible from pip and I decided to see where the issue was in the i3-xfce code. I can open up a python REPL and when I try do the following module imports from _core.py:_
_from ansible.vars import VariableManager_
_from ansible.inventory import Inventory_

Error (same for Inventory)
>>> from ansible.vars import VariableManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name VariableManager

_I installed i3-xfce from pip instead of building the module using setup.py from this repo._
My install is from an iso I got last night from xubuntu.org (16.04.3 LTS), I also installed _ansible, python-yaml, python-progressbar_ from apt, I could not find a _python-ansible._ package in apt. But, I could not find sources for that package either...

My system:
![image](https://user-images.githubusercontent.com/24324905/33181239-7337f0a4-d03d-11e7-8705-1f3ca3216c1d.png)

python modules installed with pip (i have ansible >= 2.2.0, as requirements.txt):
![image](https://user-images.githubusercontent.com/24324905/33181280-9f081fba-d03d-11e7-9c45-35e072159b5a.png)

output when running i3-xfce install:
![image](https://user-images.githubusercontent.com/24324905/33181342-e56d9db8-d03d-11e7-806e-8b982042871e.png)

**Comment by da0ist** [comment]
I have the same issue.

**Comment by j-h-m** [comment]
Someone help us out! In the screenshots it looks like they're running Xubuntu 17.04 or 17.10, could this be part of our issue somehow, an issue with ansible version?

**Comment by da0ist** [comment]
I'm no python coder, but I did manage to find out some things. Looks like they changed the way ansible is included. I managed to make a small python script from the core.py code causing the error and get it to run without error:

$ cat t.py 
import ansible
from ansible import constants as C
from ansible.parsing.dataloader import DataLoader
from ansible.vars.manager import VariableManager
from ansible.inventory.manager import InventoryManager
from ansible.playbook.play import Play
from ansible.executor.task_queue_manager import TaskQueueManager
from ansible.plugins.callback import CallbackBase

So, looks to me like the code will require a fairly large update to accommodate these changes.

**Comment by j-h-m** [comment]
Try removing ansible with pip and install ansible 2.2 from [releases.ansible.com/ansible](releases.ansible.com/ansible). That seemed to work for me in a VM. Seems that @da0ist is spot on, but this is a workaround since ansible 2.2 is structured in the way i3-xfce is programmed.

Best way to find where ansible is in your distro is to start a Python REPL and _import ansible_ then run _help(ansible)_ and it should show up at the top of the doc (just in case you don't already know...)

**Comment by j-h-m** [comment]
Seems to be an issue with Ubuntu 16.04 version of python-ansible (pip package). One may be able to remove ansible 2.4 (default installed version) then install ansible 2.2 (see link above) and run i3-xfce to install the setup.
